swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
      - type: string
        in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
      - type : string
        in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: body
        name: body
        description: Update user profile attributes
        required: true
        schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /account/{accountId}/transactions:
   get:
      security:
        - Bearer: []
      tags:
      - User Account Transactions
      summary: User Account Transactions API
      description: API for Fetching all accounts
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
      - User Account Transactions
      summary: Details of a transaction API
      description: API for Fetching details for a transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - name: accountId
        in: path
        description: User's account ID
        type: integer
        required: true
      - name: transactionId
        in: path
        description: User's account transaction ID
        type: integer
        required: true
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
      - User Account Transactions
      summary: Delete a transaction API
      description: API for deleting details for a transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionId
        description: User's account transaction ID
        type: integer
        required: true
      responses:
        '200':
          description: Transaction delete successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error    
  /account/{accountId}/transactions/{transactionId}/note:
    post:
      security:
        - Bearer: []
      tags:
      - User Account Transactions
      summary: Post a note of a transaction API
      description: API for add a note for a transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionId
        description: User's account transaction ID
        type: integer
        required: true
      - in: body
        name: body
        description: Add account note
        required: true
        schema:
            $ref: '#/definitions/AddNote'
      responses:
        '200':
          description: Note successully added
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /account/{accountId}/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
      - User Account Transactions
      summary: Update a category of a transaction API
      description: API for updating a category for a transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionId
        description: User's account transaction ID
        type: integer
        required: true
      - in: body
        name: body
        description: Update account category
        required: true
        schema:
            $ref: '#/definitions/UpdateCategory'
      responses:
        '200':
          description: Note successully update
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error 
    
        
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
        accountId:
          type: integer
          format: int64
        date:
          type: string
        description:
          type: string
        amount:
          type: number
        currency:
          type: string
        category:
          type: string
        notes:
          type: string
  AddNote:
    type: object
    properties:
        note:
          type: string
  UpdateCategory:
    type: object
    properties:
        category:
          type: string